# Generated by Django 5.2.3 on 2025-07-05 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['completed', 'created_at'], name='todos_todo_complet_ec070d_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['title', 'completed'], name='todos_todo_title_843a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['-created_at'], name='todos_todo_created_1ddebf_idx'),
        ),
    ]
