# Generated by Django 5.2.3 on 2025-07-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_create_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.user'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['owner', 'completed'], name='todos_todo_owner_i_f75edb_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['owner', 'created_at'], name='todos_todo_owner_i_8b11c5_idx'),
        ),
    ]
